<a href="https://colab.research.google.com/github/Laaliji/Detection_of_leaf-diseases_using_computer_vision/blob/main/plant_disease_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Préparation de l'environement**

### Montage de Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
path = "/content/drive/My Drive/archive(15)/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)"
!ls "$path"

test  train  valid


### Importation des bibliothèques

In [4]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os

## **Prétraitement des données**

### Prétraitement des images pour l'entraînement

In [5]:
train_dir = os.path.join(path, "train")
training_set = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)


Found 70319 files belonging to 38 classes.


### Prétraitement des images pour la validation

In [6]:
valid_dir = os.path.join(path, "valid")
validation_set = tf.keras.utils.image_dataset_from_directory(
    valid_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)


Found 17575 files belonging to 38 classes.


In [7]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [8]:
for x,y in training_set:
  print(x, x.shape)
  print(y, y.shape)
  break

tf.Tensor(
[[[[145.5  141.5  156.5 ]
   [138.5  134.5  149.5 ]
   [141.   137.   152.  ]
   ...
   [ 91.5   93.5  118.5 ]
   [ 85.25  87.25 112.25]
   [ 85.    87.   112.  ]]

  [[138.75 134.75 149.75]
   [140.75 136.75 151.75]
   [141.25 137.25 152.25]
   ...
   [ 83.25  85.25 110.25]
   [ 93.25  95.25 120.25]
   [ 90.5   92.5  117.5 ]]

  [[138.25 134.25 149.25]
   [136.5  132.5  147.5 ]
   [134.5  130.5  145.5 ]
   ...
   [ 86.75  88.75 113.75]
   [ 83.    85.   110.  ]
   [ 96.    98.   123.  ]]

  ...

  [[217.   208.   225.  ]
   [207.75 199.75 214.75]
   [210.25 202.25 217.25]
   ...
   [193.   189.   204.  ]
   [193.75 189.75 204.75]
   [194.5  190.5  205.5 ]]

  [[216.5  207.5  224.5 ]
   [220.25 212.25 227.25]
   [222.75 214.75 229.75]
   ...
   [194.75 190.75 205.75]
   [192.   188.   203.  ]
   [190.25 186.25 201.25]]

  [[221.25 212.25 229.25]
   [216.75 208.75 223.75]
   [217.5  209.5  224.5 ]
   ...
   [191.25 187.25 202.25]
   [192.   188.   203.  ]
   [192.   188.   20